# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: hcnv_tools_list
email: k.jumah@bradford.ac.uk
description: >- # this means to ignore newlines until "baseurl:"
  The site represents the available hCNVs tools that detect CNVs in WES datasets.
domain: khaled196/hcnv.github.io
baseurl: "/khaled196/hcnv.github.io.git" # the subpath of your site, e.g. /blog
<<<<<<< HEAD
<<<<<<< HEAD
url: "https://github.com/khaled196/hcnv.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ph_khaled_jumah
github_username:  khaled196
=======
url: "https://hcnv.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
>>>>>>> 8531510209af26dcd290a972014f27a530f42271
=======
url: "https://github.com/khaled196/hcnv.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ph_khaled_jumah
github_username:  khaled196
>>>>>>> 8cf7ad88f25014cf9af56e1923a92a222a199bc5

# Build settings
theme: minima
layout: hcnv_list.html
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
