#site 
title: hcnv_tools_list
description: >- # this means to ignore newlines until "baseurl:"
  The site represents the available hCNVs tools that detect CNVs in WES datasets.
domain: /users/khaled196/projects/1
baseurl: "/users/khaled196/projects/1" # the subpath of your site, e.g. /blog
url: "https://github.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
sass:
  sass_dir: assets/css
  style: compressed
highlighter: rouge
plugins:
 - jekyll-redirect-from
 - jekyll-sitemap
 - jekyll-gist
 - jekyll-relative-links

# page 
tools_dir: tools
tools:
  output: true
  permalink: /:tutorial/:path